

spring:
 
  datasource:
    url: jdbc:mysql://localhost:3306/crmapp
    password: Rajesh@12
    username: root

  jpa:
   hibernate:
     ddl-auto: create
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  
  servlet:
    multipart:
      enabled: true
  mail:
   host: smtp.gmail.com
   port: 587
   username: rajeshraina1201@gmail.com
   password: xkhfdplqyqufsumq
   properties:
     mail:
     smtp:
     starttls:
     enable: true
     auth: true






